-- 06. Identificar os 10 produtos mais vendidos:
CREATE VIEW TOP_10_PRODUCTS AS
SELECT
	PRODUCTS.PRODUCT_NAME,
	SUM(
		ORDER_DETAILS.UNIT_PRICE * ORDER_DETAILS.QUANTITY * (1.0 - ORDER_DETAILS.DISCOUNT)
	) AS SALES
FROM
	PRODUCTS
	INNER JOIN ORDER_DETAILS ON ORDER_DETAILS.PRODUCT_ID = PRODUCTS.PRODUCT_ID
GROUP BY
	PRODUCTS.PRODUCT_NAME
ORDER BYSALES DESC;
