-- 04.Separe os clientes em 5 grupos de acordo com o valor pago por cliente
CREATE VIEW VIEW_TOTAL_REVENUES_PER_CUSTOMER_GROUP AS
WITH
	CUSTOMERORDERDETAILS AS (
		SELECT
			C.COMPANY_NAME,
			OD.UNIT_PRICE,
			OD.QUANTITY,
			OD.DISCOUNT
		FROM
			CUSTOMERS C
			INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
			INNER JOIN ORDER_DETAILS OD ON OD.ORDER_ID = O.ORDER_ID
	),
	REVENUEPERCUSTOMER AS (
		SELECT
			COMPANY_NAME,
			SUM(UNIT_PRICE * QUANTITY * (1.0 - DISCOUNT)) AS TOTAL
		FROM
			CUSTOMERORDERDETAILS
		GROUP BY
			COMPANY_NAME
	)
SELECT
	COMPANY_NAME,
	TOTAL,
	NTILE(5) OVER (
		ORDER BY
			TOTAL DESC
	) AS GROUP_NUMBER
FROM
	REVENUEPERCUSTOMER
ORDER BY
	TOTAL DESC;
